#calculate BMI (body mass index)
#formula(bmi=weight/height**2)
weight=input("enter the value of wight in kg=")
height=input("enter the value of height in m=")
print(type(weight))
print(type(height))
bmi=(int(weight)/(float(height))**2)
print("the bmi value is",bmi)
#roundoff of negative 
print("The round of negative")
print(round(3235,-5))
print(round(-7893,2))